// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAccessibilityPermissions() {
  return window['go']['main']['App']['CheckAccessibilityPermissions']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function LogText(arg1) {
  return window['go']['main']['App']['LogText'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RequestAccessibilityPermissions() {
  return window['go']['main']['App']['RequestAccessibilityPermissions']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
