// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogFilePath():Promise<string>;

export function HideWindow():Promise<void>;

export function LogText(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;
