// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAccessibilityPermissions():Promise<boolean>;

export function ClearAllData():Promise<void>;

export function GetDatabasePath():Promise<string>;

export function GetLogEntries(arg1:number):Promise<Array<main.LogEntry>>;

export function GetLogEntriesCount():Promise<number>;

export function GetSettings():Promise<main.Settings>;

export function HideWindow():Promise<void>;

export function IsFirstRun():Promise<boolean>;

export function LogText(arg1:string):Promise<void>;

export function OpenSettings():Promise<void>;

export function ProcessCommand(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RenderMarkdown(arg1:string):Promise<string>;

export function RequestAccessibilityPermissions():Promise<void>;

export function SearchLogEntries(arg1:string,arg2:number):Promise<Array<main.LogEntry>>;

export function SetSettings(arg1:main.Settings):Promise<void>;

export function ShowInstructions():Promise<void>;

export function ShowWindow():Promise<void>;
