// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAccessibilityPermissions() {
  return window['go']['main']['App']['CheckAccessibilityPermissions']();
}

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function ClearDashboardFiles() {
  return window['go']['main']['App']['ClearDashboardFiles']();
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function GetDashboardPath() {
  return window['go']['main']['App']['GetDashboardPath']();
}

export function GetDatabasePath() {
  return window['go']['main']['App']['GetDatabasePath']();
}

export function GetEntriesByTags(arg1, arg2) {
  return window['go']['main']['App']['GetEntriesByTags'](arg1, arg2);
}

export function GetEntryByID(arg1) {
  return window['go']['main']['App']['GetEntryByID'](arg1);
}

export function GetEntryForEdit(arg1) {
  return window['go']['main']['App']['GetEntryForEdit'](arg1);
}

export function GetEntryPreview(arg1) {
  return window['go']['main']['App']['GetEntryPreview'](arg1);
}

export function GetLogEntries(arg1) {
  return window['go']['main']['App']['GetLogEntries'](arg1);
}

export function GetLogEntriesCount() {
  return window['go']['main']['App']['GetLogEntriesCount']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function LogText(arg1) {
  return window['go']['main']['App']['LogText'](arg1);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function ProcessCommand(arg1) {
  return window['go']['main']['App']['ProcessCommand'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RenderMarkdown(arg1) {
  return window['go']['main']['App']['RenderMarkdown'](arg1);
}

export function RequestAccessibilityPermissions() {
  return window['go']['main']['App']['RequestAccessibilityPermissions']();
}

export function SearchLogEntries(arg1, arg2) {
  return window['go']['main']['App']['SearchLogEntries'](arg1, arg2);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function ShowInstructions() {
  return window['go']['main']['App']['ShowInstructions']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function UpdateEntry(arg1, arg2) {
  return window['go']['main']['App']['UpdateEntry'](arg1, arg2);
}
