// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearAllData():Promise<void>;

export function DeleteEntry(arg1:number):Promise<void>;

export function GetDatabasePath():Promise<string>;

export function GetEntryByID(arg1:number):Promise<main.LogEntry>;

export function GetEntryForEdit(arg1:number):Promise<string>;

export function GetEntryPreview(arg1:number):Promise<string>;

export function GetLogEntries(arg1:number):Promise<Array<main.LogEntry>>;

export function GetLogEntriesCount():Promise<number>;

export function GetMostRecentEntry():Promise<main.LogEntry>;

export function GetSettings():Promise<main.Settings>;

export function GetTags():Promise<Array<main.Tag>>;

export function HideWindow():Promise<void>;

export function IsFirstRun():Promise<boolean>;

export function LogText(arg1:string):Promise<void>;

export function OpenSettings():Promise<void>;

export function ProcessCommand(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RenderMarkdown(arg1:string):Promise<string>;

export function SetSettings(arg1:main.Settings):Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateEntry(arg1:number,arg2:string):Promise<void>;
